---
# webapp vars
war_url: "https://raw.githubusercontent.com/aliusmiles/training-ansible/master/files/"
webapp_url: "{{ war_url }}{{ webapp_name }}.war"
webapp_md5_url: "{{ war_url }}{{ webapp_name }}.war.md5"
webapp_dest: "/var/lib/tomcat/webapps/{{ webapp_name }}.war"
